"""add watchlist table

Revision ID: 5f8de0fcfe30
Revises: 5aa6f6cfd52d
Create Date: 2026-09-30 17:10:26.316233

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f8de0fcfe30"
down_revision: str | Sequence[str] | None = "5aa6f6cfd52d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("watchlist"):
        op.create_table(
            "watchlist",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("film_id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(["film_id"], ["films.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("user_id", "film_id", name="uq_user_film_watchlist"),
        )
        op.create_index(op.f("ix_watchlist_film_id"), "watchlist", ["film_id"], unique=False)
        op.create_index(op.f("ix_watchlist_user_id"), "watchlist", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("watchlist"):
        op.drop_index(op.f("ix_watchlist_user_id"), table_name="watchlist")
        op.drop_index(op.f("ix_watchlist_film_id"), table_name="watchlist")
        op.drop_table("watchlist")
    # ### end Alembic commands ###
